PROGRAM MAIN

IMPLICIT NONE

#include "sparallelmethod.intfb.h"

CHARACTER*128 :: CLMETHOD, CLNAME
LOGICAL :: LLMATCH
INTEGER :: I

OPEN (88, FILE='input.txt', FORM='FORMATTED', STATUS='OLD')
OPEN (99, FILE='output.txt', FORM='FORMATTED', STATUS='UNKNOWN')

DO 

  READ (88, *, END=999) CLMETHOD, CLNAME
  CALL SPARALLELMETHOD (TRIM (CLMETHOD), TRIM (CLNAME), LLMATCH)
  WRITE (99, '(A20," ",A30," ",L1)') TRIM (CLMETHOD), TRIM (CLNAME), LLMATCH

ENDDO

999 CONTINUE

CLOSE (99)
CLOSE (88)

END
