PROGRAM MAIN

IMPLICIT NONE

#include "sparallelmethod.intfb.h"

CHARACTER*128 :: CLMETHOD, CLNAME
LOGICAL :: LLMATCH
REAL :: ZS, ZF
INTEGER :: I

CALL SPARALLELMETHOD ('A', 'B', LLMATCH)

OPEN (88, FILE='input.txt', FORM='FORMATTED', STATUS='OLD')
OPEN (99, FILE='output.txt', FORM='FORMATTED', STATUS='UNKNOWN')

CALL CPU_TIME (ZS)

DO 

  READ (88, *, END=999) CLMETHOD, CLNAME
  CALL SPARALLELMETHOD (TRIM (CLMETHOD), TRIM (CLNAME), LLMATCH)
  WRITE (99, '(A20," ",A30," ",L1)') TRIM (CLMETHOD), TRIM (CLNAME), LLMATCH

ENDDO

999 CONTINUE

CALL CPU_TIME (ZF)

CLOSE (99)
CLOSE (88)

WRITE (*, '(F18.6)') ZF - ZS

END
