PROGRAM MAIN

IMPLICIT NONE

#include "sparallelmethod.intfb.h"

CHARACTER*128 :: CLMETHOD, CLNAME
LOGICAL :: LLMATCH

DO
  READ (5, *, END=999) CLMETHOD, CLNAME
  CALL SPARALLELMETHOD (TRIM (CLMETHOD), TRIM (CLNAME), LLMATCH)
  WRITE (6, '(A20," ",A30," ",L1)') TRIM (CLMETHOD), TRIM (CLNAME), LLMATCH
ENDDO

999 CONTINUE

END
