SUBROUTINE SPARALLELMETHOD (CDMETHOD, CDNAME, LDMATCH) 

IMPLICIT NONE

CHARACTER (LEN=*),   INTENT (IN) :: CDMETHOD
CHARACTER (LEN=*),   INTENT (IN) :: CDNAME
LOGICAL,             INTENT (OUT) :: LDMATCH

LDMATCH = LPARALLELMETHOD (CDMETHOD, CDNAME)

CONTAINS

LOGICAL FUNCTION LPARALLELMETHOD (CDMETHOD, CDNAME) 

USE XRD_UNIX_ENV

IMPLICIT NONE

CHARACTER (LEN=*),   INTENT (IN) :: CDMETHOD
CHARACTER (LEN=*),   INTENT (IN) :: CDNAME


CHARACTER (LEN=*), PARAMETER :: CLFILE = 'lparallelmethod.txt'
CHARACTER (LEN=256) :: CLMETHOD1, CLMETHOD2
CHARACTER (LEN=256) :: CLMETHOD

CHARACTER (LEN=256), ALLOCATABLE, SAVE :: CLNAMES (:)
CHARACTER (LEN=256), ALLOCATABLE, SAVE :: CLMETHODS (:)
INTEGER, ALLOCATABLE, SAVE :: ILNAMES (:)
LOGICAL, SAVE :: LLVERBOSE = .FALSE.
LOGICAL, SAVE :: LLINIT = .FALSE.

INTEGER :: ICOUNT, IERR, I
INTEGER, SAVE :: IDX = -1
INTEGER :: ILNAME
CHARACTER (LEN=16) :: CLENV

IF (.NOT. LLINIT) THEN

  CALL XRD_COUNTLINES (ICOUNT, CLFILE, IERR)
  CALL GETENV ('LPARALLELMETHOD_VERBOSE', CLENV)
  LLVERBOSE = TRIM (CLENV) /= '' .AND. TRIM (CLENV) /= '0'

  IF (IERR == 0) THEN

    ALLOCATE (CLNAMES (ICOUNT), CLMETHODS (ICOUNT), ILNAMES (ICOUNT))
    OPEN (77, FILE=CLFILE, FORM='FORMATTED')
    DO I = 1, ICOUNT
      READ (77, *) CLMETHODS (I), CLNAMES (I)
      ILNAMES (I) = LEN_TRIM (CLNAMES (I))
      CALL LPARALLELMETHOD_BBT_ADD (TRIM (CLNAMES (I)), TRIM (CLMETHODS (I)))
    ENDDO
    CLOSE (77)

    IF (LLVERBOSE) THEN
      WRITE (0, *) "------ "//TRIM (CLFILE)//" ------"
      DO I = 1, SIZE (CLNAMES)
        WRITE (0, '(A32," ",A)') CLMETHODS (I), TRIM (CLNAMES (I))
      ENDDO
      WRITE (0, *) "------ "//TRIM (CLFILE)//" ------"
    ENDIF

  ENDIF

  LLINIT = .TRUE.

ENDIF

#ifndef UNDEF

CALL XRD_UPPER_CASE (CLMETHOD1, CDMETHOD)


ILNAME = LEN_TRIM (CDNAME)

IF (ALLOCATED (CLNAMES)) THEN
  

  ! Try previous match first

  IF ((1 <= IDX) .AND. (IDX <= SIZE (CLNAMES))) THEN
    IF (CLMETHODS (IDX)(1:1) /= '#') THEN
      IF (EQUAL (CDNAME, ILNAME, CLNAMES (IDX), ILNAMES (IDX))) THEN
        CALL XRD_UPPER_CASE (CLMETHOD2, CLMETHODS (IDX))
        LPARALLELMETHOD = TRIM (CLMETHOD1) == TRIM (CLMETHOD2)
        GOTO 999
      ENDIF
    ENDIF
  ENDIF

  
  IDX = -1

  DO I = 1, SIZE (CLNAMES)
    IF (CLMETHODS (I)(1:1) /= '#') THEN
      IF (EQUAL (CDNAME, ILNAME, CLNAMES (I), ILNAMES (I))) THEN
        CALL XRD_UPPER_CASE (CLMETHOD2, CLMETHODS (I))
        LPARALLELMETHOD = TRIM (CLMETHOD1) == TRIM (CLMETHOD2)
        IDX = I
        GOTO 999
      ENDIF
    ENDIF
  ENDDO
ENDIF

LPARALLELMETHOD = (CLMETHOD1 == "OPENMP") .OR. (CLMETHOD1 == "OPENMPMETHOD")

999 CONTINUE

IF (LLVERBOSE .AND. LPARALLELMETHOD) THEN
  IF (IDX > 0) THEN
    WRITE (0, '(A32," ",A)') CLMETHODS (I), TRIM (CLNAMES (I))
  ELSE
    WRITE (0, '(A32," ",A)') CLMETHOD1, TRIM (CDNAME)
    CALL FLUSH(0)
  ENDIF
ENDIF

#else

CALL LPARALLELMETHOD_BBT_GET (CDNAME, CLMETHOD)

IF (CDMETHOD (1:1) /= ' ') THEN
  LPARALLELMETHOD = EQUAL (CLMETHOD, LEN_TRIM (CLMETHOD), CDMETHOD, LEN_TRIM (CDMETHOD))
  RETURN
ENDIF

LPARALLELMETHOD = (CDMETHOD == "OPENMP") .OR. (CDMETHOD == "OPENMPMETHOD")

#endif

END FUNCTION

LOGICAL FUNCTION EQUAL (CDSTR1, KLEN1, CDSTR2, KLEN2)

CHARACTER (LEN=*) :: CDSTR1, CDSTR2
INTEGER :: KLEN1, KLEN2

INTEGER :: IC
CHARACTER :: C1, C2
INTEGER*1 :: IC1, IC2

EQUAL = .TRUE.

IF (KLEN1 /= KLEN2) THEN
  EQUAL = .FALSE.
  RETURN
ENDIF

DO IC = 1, KLEN1
  C1 = CDSTR1 (IC:IC)
  C2 = CDSTR2 (IC:IC)

  IC1 = ICHAR (C1)
  IC2 = ICHAR (C2)

  IF ((97 <= IC1) .AND. (IC1 <= 122)) IC1 = IC1 + 32
  IF ((97 <= IC2) .AND. (IC2 <= 122)) IC2 = IC2 + 32

  IF (IC1 /= IC2) THEN
    EQUAL = .FALSE.
    RETURN
  ENDIF
  
ENDDO

END FUNCTION

END SUBROUTINE
