SUBROUTINE SPARALLELMETHOD (CDMETHOD, CDNAME, LDMATCH) 

IMPLICIT NONE

CHARACTER (LEN=*),   INTENT (IN) :: CDMETHOD
CHARACTER (LEN=*),   INTENT (IN) :: CDNAME
LOGICAL,             INTENT (OUT) :: LDMATCH

LDMATCH = LPARALLELMETHOD (CDMETHOD, CDNAME)

CONTAINS

LOGICAL FUNCTION LPARALLELMETHOD (CDMETHOD, CDNAME) 

USE XRD_UNIX_ENV

IMPLICIT NONE

CHARACTER (LEN=*),   INTENT (IN) :: CDMETHOD
CHARACTER (LEN=*),   INTENT (IN) :: CDNAME


CHARACTER (LEN=*), PARAMETER :: CLFILE = 'lparallelmethod.txt'
CHARACTER (LEN=256) :: CLMETHOD1, CLMETHOD2

CHARACTER (LEN=256), ALLOCATABLE, SAVE :: CLNAMES (:)
CHARACTER (LEN=256), ALLOCATABLE, SAVE :: CLMETHODS (:)
LOGICAL, SAVE :: LLVERBOSE = .FALSE.
LOGICAL, SAVE :: LLINIT = .FALSE.

INTEGER :: ICOUNT, IERR, I, IDX
CHARACTER (LEN=16) :: CLENV

IF (.NOT. LLINIT) THEN

  CALL XRD_COUNTLINES (ICOUNT, CLFILE, IERR)
  CALL GETENV ('LPARALLELMETHOD_VERBOSE', CLENV)
  LLVERBOSE = TRIM (CLENV) /= '' .AND. TRIM (CLENV) /= '0'

  IF (IERR == 0) THEN

    ALLOCATE (CLNAMES (ICOUNT), CLMETHODS (ICOUNT))
    OPEN (77, FILE=CLFILE, FORM='FORMATTED')
    DO I = 1, ICOUNT
      READ (77, *) CLMETHODS (I), CLNAMES (I)
    ENDDO
    CLOSE (77)

    IF (LLVERBOSE) THEN
      WRITE (0, *) "------ "//TRIM (CLFILE)//" ------"
      DO I = 1, SIZE (CLNAMES)
        WRITE (0, '(A32," ",A)') CLMETHODS (I), TRIM (CLNAMES (I))
      ENDDO
      WRITE (0, *) "------ "//TRIM (CLFILE)//" ------"
    ENDIF

  ENDIF

  LLINIT = .TRUE.

ENDIF

CALL XRD_UPPER_CASE (CLMETHOD1, CDMETHOD)

IDX = -1

IF (ALLOCATED (CLNAMES)) THEN
  DO I = 1, SIZE (CLNAMES)
    IF (CLMETHODS (I)(1:1) /= '#') THEN
!     IF (TRIM (CDNAME) == TRIM (CLNAMES (I))) THEN
      IF (EQUAL (CDNAME, CLNAMES (I))) THEN
        CALL XRD_UPPER_CASE (CLMETHOD2, CLMETHODS (I))
        LPARALLELMETHOD = TRIM (CLMETHOD1) == TRIM (CLMETHOD2)
        IDX = I
        GOTO 999
      ENDIF
    ENDIF
  ENDDO
ENDIF

LPARALLELMETHOD = (CLMETHOD1 == "OPENMP") .OR. (CLMETHOD1 == "OPENMPMETHOD")

999 CONTINUE

IF (LLVERBOSE .AND. LPARALLELMETHOD) THEN
  IF (IDX > 0) THEN
    WRITE (0, '(A32," ",A)') CLMETHODS (I), TRIM (CLNAMES (I))
  ELSE
    WRITE (0, '(A32," ",A)') CLMETHOD1, TRIM (CDNAME)
    CALL FLUSH(0)
  ENDIF
ENDIF

END FUNCTION

LOGICAL FUNCTION EQUAL (CDSTR1, CDSTR2)

CHARACTER (LEN=*) :: CDSTR1, CDSTR2

INTEGER :: IC, IL
CHARACTER :: C1, C2
INTEGER*1 :: IC1, IC2

EQUAL = .TRUE.

IL = MIN (LEN (CDSTR1), LEN (CDSTR2))

DO IC = 1, IL
  C1 = CDSTR1 (IC:IC)
  C2 = CDSTR2 (IC:IC)

  IC1 = ICHAR (C1)
  IC2 = ICHAR (C2)

  IF ((97 <= IC1) .AND. (IC1 <= 122)) IC1 = IC1 + 32
  IF ((97 <= IC2) .AND. (IC2 <= 122)) IC2 = IC2 + 32

  IF (IC1 /= IC2) THEN
    EQUAL = .FALSE.
    RETURN
  ENDIF
  
ENDDO

END FUNCTION

END SUBROUTINE
