INTERFACE
SUBROUTINE SPARALLELMETHOD (CDMETHOD, CDNAME, LDMATCH)
IMPLICIT NONE
CHARACTER (LEN=*),   INTENT (IN) :: CDMETHOD
CHARACTER (LEN=*),   INTENT (IN) :: CDNAME
LOGICAL,             INTENT (OUT) :: LDMATCH
END SUBROUTINE


END INTERFACE
